import cv2 as cv
import numpy as np
import torch
import os
import torch.nn as nn
from torchvision import transforms
from PIL import Image

class BaseCNN(nn.Module):
    def __init__(self, num_classes: int):
        super(BaseCNN, self).__init__()
        self.conv_layers = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2),
            nn.Conv2d(16, 32, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2, 2)
        )
        self.fc_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 16 * 16, 128), nn.ReLU(), nn.Dropout(0.5),
            nn.Linear(128, num_classes)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.conv_layers(x)
        x = self.fc_layers(x)
        return x

MODEL_REGISTRY = {
    "cnn_v1": {
        "class": BaseCNN,
        "url": "https://github.com/keshavshankar08/TCASLCore/releases/download/v1.0.0/cnn_v1.pth"
    },
    # "snn_v1": {
    #     "class": BaseSNN,
    #     "url": "https://github.com/keshavshankar08/TCASLCore/releases/download/v_._._/snn_v1.pth"
    # }
}

class TCASL:
    def __init__(self, arch: str = "cnn_v1", model_path: str = None):
        """
        Initializes the TCASL classifier.

        :param arch: The architecture tag to use.
        :param model_path: Optional local path to the weights. If None, it auto-downloads.
        """
        self.classes = [chr(i) for i in range(ord('a'), ord('z') + 1)] + ['none']
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        if arch not in MODEL_REGISTRY:
            raise ValueError(f"Architecture '{arch}' not found. Available: {list(MODEL_REGISTRY.keys())}")
        
        arch_info = MODEL_REGISTRY[arch]
        ModelClass = arch_info["class"]
        download_url = arch_info["url"]

        self.model = ModelClass(num_classes=len(self.classes)).to(self.device)

        self.transform = transforms.Compose([
            transforms.Grayscale(num_output_channels=1), 
            transforms.Resize((128, 128)), 
            transforms.ToTensor()
        ])

        self._load_model(model_path, download_url)

    def _load_model(self, path: str, download_url: str) -> None:
        if path and os.path.exists(path):
            state_dict = torch.load(path, map_location=self.device, weights_only=True)
        else:
            state_dict = torch.hub.load_state_dict_from_url(
                download_url, 
                map_location=self.device, 
                weights_only=True,
                check_hash=False
            )
            
        self.model.load_state_dict(state_dict)
        self.model.eval()

    def preprocess_frame(self, frame: np.ndarray) -> np.ndarray:
        """
        Center-crops a standard video frame to a square and resizes it to the required 128x128 resolution.

        :param frame: A raw grayscale image array of any shape.

        :return: A 128x128 cropped and resized grayscale image array.
        """
        h, w = frame.shape
        min_dim = min(h, w)
        start_x = (w // 2) - (min_dim // 2)
        start_y = (h // 2) - (min_dim // 2)
        square_img = frame[start_y:start_y+min_dim, start_x:start_x+min_dim]
        return cv.resize(square_img, (128, 128))
    
    def compute_temporal_contrast(self, previous_frame: np.ndarray, current_frame: np.ndarray, threshold: int = 20) -> np.ndarray:
        """
        Computes the temporal contrast between two consecutive frames to emulate a Dynamic Vision Sensor (DVS).

        :param previous_frame: The previous grayscale frame.
        :param current_frame: The current grayscale frame (must match previous_frame shape).
        :param threshold: The pixel intensity difference required to trigger an event. Defaults to 20.

        :return: A temporal contrast frame where 127 is neutral, 255 is positive polarity, and 0 is negative polarity.
        """
        temp_contrast_frame = np.full(previous_frame.shape, 127, dtype=np.uint8)
        diff_frame = current_frame.astype(np.float32) - previous_frame.astype(np.float32)
        temp_contrast_frame[diff_frame > threshold] = 255
        temp_contrast_frame[diff_frame < -threshold] = 0
        return temp_contrast_frame

    def predict(self, tc_frame: np.ndarray) -> str:
        """
        Runs neural network inference on a temporal contrast frame to predict the ASL character.

        :param tc_frame: The temporal contrast frame generated by compute_temporal_contrast.

        :return: The predicted class label (a single lowercase letter 'a'-'z', or 'none').
        """
        tc_image = Image.fromarray(tc_frame)
        input_tensor = self.transform(tc_image).unsqueeze(0).to(self.device)

        with torch.no_grad():
            outputs = self.model(input_tensor)
            _, predicted = torch.max(outputs.data, 1)
            pred_class = self.classes[predicted.item()]

        return pred_class